server.port=8100
#actuator endpoint
management.endpoints.web.exposure.include=*


spring.profiles.active=native


spring.cloud.config.server.native.search-locations=file:///D:/training/weather/properties


