server.port=8100


management.endpoints.web.exposure.include=*


# Config server settings
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:///d:/training/weather/properties



