
spring.cloud.gateway.routes[100].id=swagger-resources
spring.cloud.gateway.routes[100].uri=http://localhost:${server.port}
spring.cloud.gateway.routes[100].predicates[0]=Path=/swagger-ui/**,/swagger-ui.html,/webjars/**,/api-docs/**
spring.cloud.gateway.routes[100].order=-1


springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.config-url=/swagger-ui/swagger-config
springdoc.swagger-ui.urls[0].name=Details Service
springdoc.swagger-ui.urls[0].url=/details/api-docs
springdoc.swagger-ui.urls[1].name=Data Service
springdoc.swagger-ui.urls[1].url=/dataservice/api-docs
springdoc.swagger-ui.urls[2].name=Search Service
springdoc.swagger-ui.urls[2].url=/search/api-docs