server.port={cipher}AQAuc2lt6gbH7Hctl/e9sqXHrHv2TxMgXBNky+g+jL04qkJMf4UVL0AiqbvPoG2HuCowEYObueHjqNQi1LwnXkbxeZeKHKbW1p5ldSM485ScSQy8YjX2qR4NVVNxuL6tdeZhmJgIII4uccccnoREI80xKGkWwljDBx8lixM+SrP2SoZiXfbEjdlrayzYJcnD0ste1X2YfcSIfV8mUJ8knxLP/kT1Vemt0MRKbcpEkRbTUQ7LiLaYoL1VqyNq05dwvukQV09wP69QYqrko2l3uE8oodqx0JjDmrfIAPS9hvI6XJ0/bfjaaRMxtUJleE7OrO7wujzwk9oprqaT6jXGqUGl57VesMoLig2MwvWW1w9P62dQqly6d3+dakttUSlwFMI=
# Hikari config
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.idle-timeout=300000

# MongoDB config
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=student_db
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.field-naming-strategy=org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
spring.data.mongodb.uuid-representation=standard
spring.data.mongodb.write-concern=ACKNOWLEDGED
spring.data.mongodb.read-preference=primary

spring.data.mongodb.username={cipher}AQAJMXpoc2BMAeC5x90roPjthKWVHillKqPKAGh8yR+jfwQCkzr6Kp+feTki87anqaI+cubA5L2HfH+nemi+UJjIZH5/H+NKS8N8mhSaOvoOjLiZFR08F00rEnUpz6Gz2/0tur9rYazLPi0mM97fYNXacZdBxobKNNqM3O8qJbwvrhNn2pP7v3aVZ6NqsCvg6W2jlB/tOmDg+Y84pjhPf8HaSUd92YViicU85+clZCKRAYG+IS0R/LuSfYh7JyTp1AeSXtSPHUtO3OTgI2LopOsA0UHXwucr9iLskWoWQ5Bq7Emsm68MdiEjzWzYV1N4hDuh45Xd00FUtJexKhYeLYu9M2PNpGLmYOZWcQE2FUIkGMbHVqxUAVod5xJL7+5gfeU=

spring.data.mongodb.password={cipher}AQBbCHe6JOrFMbGaYh3+6RGwQRU3l+S0LyIds8ETwKcWAtNOLHXbHadN+sa/N6605KckSk+vm867vl/DuGD4lFYqM5WwV9qzrkxzeuFWXNQtzJVenAqkroM/WFEicb47pDsqJbX20ODy7E/6sCTg551L46kteJ9ZZgYh9ZowMjz7usqbcxOthtJqOHbwvzy/Z9JksvYzMSYp/qxR6lYBTsXustzvydhd3DLVhRfGqQGvejlQ/Gcpg5WDovKobtJPE+Uyl2rfFIntrl8+Ikd4RS7sm4Zzin/XdMRxsHE6jwKIchZvzx8w+PoQTuBWolIz/gISuuxrU5Yj40OnlMe5RxPrd0n1+iqxDITSHUtS4cKr758gb8qLk7VrJUTJJVJ2Srg=

# spring.data.mongodb.username=testuser
# spring.data.mongodb.password=testpassword
# Eureka config
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Actuator config
management.endpoints.web.exposure.include=*,prometheus,health,info,metrics
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

# Add application name tag to metrics
spring.application.name= dataservice

#Hystrix config
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=5000

# OpenAPI Configuration - Simplified
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.disable-swagger-default-url=true

# Correct path mapping for access through gateway
springdoc.swagger-ui.configUrl=/swagger-ui/swagger-config.json
springdoc.swagger-ui.url=/v3/api-docs
springdoc.pathsToMatch=/**