server.port={cipher}AQBNfmE5mENwbTZIRfT8NsFKN7tCL3iEuwmGQcLu8NrMQZ8RcX+V4nrFzZOHCbD3KmJZAn7d4ZJn+A5g7+VnNJLuOAf4Nh0KHohcnAAP2cz74F9n6CdUARk+/73KBN53VKwS3BA+05TXD7AHSb5aqnCVAYEcyGmmkIaTkbvh6CD5PCc0RWH7sSPtuhJc83EW2yuBRtq6iyKetooaDSBF0s1YIvl2GEQpLDz8hnSZyp2erJU7w3ihKrBx3x8oaVmcND4IKelXF+VSKd4rLCvgZR5Hi/cvxGvHCZvwRpD7MYoRrNXwJk4DJ6x9R5K0X0dkVnhfrga8YnoRn9z1KcbLC4qG9Pm66pVFb010Xh81BnJaRIQsxGFVtfrtep2aGs2SBrk=
spring.application.name=details

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Actuator config
management.endpoints.web.exposure.include=*,prometheus,health,info,metrics
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.endpoints.web.base-path=/actuator

spring.mvc.contentnegotiation.favor-parameter=true
spring.mvc.contentnegotiation.media-types.prometheus=application/openmetrics-text
spring.mvc.contentnegotiation.media-types.txt=text/plain

#indicates the frequency the client sends heartbeat to server to indicate that it is alive.
eureka.instance.lease-renewal-interval-in-seconds=10

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# OpenAPI Configuration - Simplified
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.disable-swagger-default-url=true

springdoc.swagger-ui.configUrl=/swagger-ui/swagger-config.json
springdoc.pathsToMatch=/**


