server.port=9400
spring.application.name=details

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Actuator config
management.endpoints.web.exposure.include=*,prometheus,health,info,metrics
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true


#indicates the frequency the client sends heartbeat to server to indicate that it is alive.
eureka.instance.lease-renewal-interval-in-seconds=10

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
