server.port=8761

# 
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# 
eureka.instance.hostname=localhost
eureka.client.serviceUrl.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/

# 
eureka.server.enable-self-preservation=false

# 
management.endpoints.web.exposure.include=*,prometheus,health,info,metrics
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

#incicates the duration the server waits since it received the last heartbeat before it can evict an instance from its registry
eureka.instance.lease-expiration-duration-in-seconds=20
