server.port=8200

# # Weather module route
# spring.cloud.gateway.routes[0].id=weatherModule
# spring.cloud.gateway.routes[0].uri=lb://search
# spring.cloud.gateway.routes[0].predicates[0]=Path=/weather/**

# Search combined route
spring.cloud.gateway.routes[0].id=search
spring.cloud.gateway.routes[0].uri=lb://search
spring.cloud.gateway.routes[0].predicates[0]=Path=/search/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# Details module route - Add StripPrefix filter
spring.cloud.gateway.routes[1].id=detailsModule
spring.cloud.gateway.routes[1].uri=lb://details
spring.cloud.gateway.routes[1].predicates[0]=Path=/details/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# Dataservice route - Add StripPrefix filter
spring.cloud.gateway.routes[2].id=dataservice
spring.cloud.gateway.routes[2].uri=lb://dataservice
spring.cloud.gateway.routes[2].predicates[0]=Path=/dataservice/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

# # Search combined route
# spring.cloud.gateway.routes[0].id=search-combined
# spring.cloud.gateway.routes[0].uri=lb://search
# spring.cloud.gateway.routes[0].predicates[0]=Path=/search/combined/**
# spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# # Dataservice Actuator
# spring.cloud.gateway.routes[4].id=dataservice-actuator
# spring.cloud.gateway.routes[4].uri=lb://dataservice
# spring.cloud.gateway.routes[4].predicates[0]=Path=/dataservice/actuator/**
# spring.cloud.gateway.routes[4].filters[0]=RewritePath=/dataservice/actuator/(?<segment>.*), /actuator/${segment}

# # Details Actuator
# spring.cloud.gateway.routes[5].id=details-actuator
# spring.cloud.gateway.routes[5].uri=lb://details
# spring.cloud.gateway.routes[5].predicates[0]=Path=/details/actuator/**
# spring.cloud.gateway.routes[5].filters[0]=RewritePath=/details/actuator/(?<segment>.*), /actuator/${segment}

# # Search Actuator
# spring.cloud.gateway.routes[6].id=search-actuator
# spring.cloud.gateway.routes[6].uri=lb://search
# spring.cloud.gateway.routes[6].predicates[0]=Path=/search/actuator/**
# spring.cloud.gateway.routes[6].filters[0]=RewritePath=/search/actuator/(?<segment>.*), /actuator/${segment}

spring.cloud.gateway.discovery.locator.enabled=true
myservice.ribbon.NFLoadBalancerRuleClassName=com.netflix.loadbalancer.RandomRule

#eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# gateway actuator
management.endpoints.web.exposure.include=*,prometheus,health,info,metrics
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true


eureka.instance.lease-renewal-interval-in-seconds=10
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/